spring:
  profiles:
    active: local
  batch:
    job:
      names: ${job.name:NONE} # 파라미터로 넘어온 job만 실행 시킨다.

logging.level.org.springframework.batch: DEBUG
---
spring:
  profiles: local
  datasource:
    hikari:
      jdbc-url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
      username: sa
      password:
      driver-class-name: org.h2.Driver
---
spring:
  profiles: mysql
  datasource:
    hikari:
      jdbc-url: jdbc:mysql://localhost:3306/spring_batch
      username: jordan
      password: 1234
      driver-class-name: com.mysql.jdbc.Driver
---

